fixtures:
  forge_modules:
    archive: 'camptocamp-archive'
    buildenv: 'camptocamp-buildenv'
    concat: 'puppetlabs-concat'
    python: 'camptocamp-python'
    stdlib: 'puppetlabs-stdlib'
  symlinks:
    rdiff_backup: "#{source_dir}"
